# Generated by Django 2.2 on 2021-08-26 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokerboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Name of Pokerboard', max_length=20, unique=True)),
                ('description', models.CharField(help_text='Description', max_length=100)),
                ('estimation_type', models.CharField(choices=[('1', 'series'), ('2', 'even'), ('3', 'odd'), ('4', 'fibonacci')], help_text='Estimation type', max_length=20)),
                ('duration', models.IntegerField(help_text='Duration for voting')),
                ('status', models.CharField(max_length=20)),
                ('manager', models.ForeignKey(help_text='Owner of Pokerboard', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
