# Generated by Django 2.2 on 2021-08-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerboard',
            name='estimation_type',
            field=models.CharField(choices=[('SERIES', 'Series'), ('EVEN', 'Even'), ('ODD', 'Odd'), ('FIBONACCI', 'Fibonacci')], help_text='Estimation type', max_length=20),
        ),
        migrations.AlterField(
            model_name='pokerboard',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('ENDED', 'Ended')], default='', max_length=20),
        ),
    ]
