# Generated by Django 2.2 on 2021-09-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
