# Generated by Django 2.2 on 2021-08-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0003_auto_20210826_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerboard',
            name='estimation_type',
            field=models.CharField(choices=[('SERIES', 'Series'), ('EVEN', 'Even'), ('ODD', 'Odd'), ('FIBONACCI', 'Fibonacci')], default='SERIES', help_text='Estimation type', max_length=20),
        ),
    ]
