# Generated by Django 2.2 on 2021-08-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0004_auto_20210826_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerboard',
            name='duration',
            field=models.IntegerField(help_text='Duration for voting (in secs)'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.SlugField(help_text='Ticket ID imported from JIRA')),
                ('estimate', models.IntegerField(help_text='Final estimate of ticket')),
                ('rank', models.IntegerField(help_text='Rank of ticket')),
                ('pokerboard', models.ForeignKey(help_text='Pokerboard to which ticket belongs', on_delete=django.db.models.deletion.CASCADE, to='pokerboard.Pokerboard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
