# Generated by Django 2.2 on 2021-08-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0005_auto_20210828_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estimate',
            field=models.IntegerField(help_text='Final estimate of ticket', null=True),
        ),
    ]
