# Generated by Django 2.2 on 2021-08-30 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0002_auto_20210830_1201'),
        ('pokerboard', '0006_auto_20210828_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitee', models.EmailField(help_text='Person invited', max_length=254)),
                ('role', models.CharField(choices=[('SPECTATOR', 'Spectator'), ('CONTRIBUTOR', 'Contributor'), ('GUEST', 'Guest')], help_text='Role', max_length=10)),
                ('is_accepted', models.BooleanField(default=False, help_text='Accepted or not?')),
                ('invite_time', models.DateTimeField(help_text='Time at which invited')),
                ('group', models.ForeignKey(help_text='Name of group through which invited, if invited via group', null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('inviter', models.ForeignKey(help_text='Invited by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pokerboard', models.ForeignKey(help_text='Pokerboard', on_delete=django.db.models.deletion.CASCADE, to='pokerboard.Pokerboard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
