# Generated by Django 2.2 on 2021-09-12 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboard', on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='pokerboard.Pokerboard'),
        ),
    ]
