# Generated by Django 2.2 on 2021-08-17 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text='Email Address', max_length=50, unique=True)),
                ('first_name', models.CharField(help_text='First Name of User', max_length=150)),
                ('last_name', models.CharField(help_text='Last Name of User', max_length=150)),
                ('is_staff', models.BooleanField(default=False, help_text='This user can access admin panel')),
                ('is_admin', models.BooleanField(default=False, help_text='This user has all permissions without explicitly assigning them')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
