# Generated by Django 2.2 on 2021-08-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(help_text='Name of the group', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='groupuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
